### ISSUE TITLE
dynamically add artwork now?

### ISSUE THREAD

**Issue by verbes4** [SandwichFox/MBCord#14]
**Describe the feature/change you'd like**
im 99% sure discord has added the ability to dynamically change rich presence images, i havent used the feature myself yet but ive seen apps like premid do it, for example with apple music. i noticed on the faq it says its not possible so please correct me if im wrong 

**Additional context**

**Comment by SandwichFox** [comment]
i can look into it, i will update you on this matter.

**Comment by zeroquinc** [comment]
Thanks for continuing this project! And love to see this as well! :)

**Comment by Chicken** [comment]
Indeed possible, the `largeImageKey` and `smallImageKey` in the `rpc.setActivity(...)` can be string urls pointing to an image resource.
For example, I achieved dynamic **Jellyfin** series episode covers for myself locally by adding this to it
```js
largeImageKey: `${mbc.serverAddress}/Items/${NPItem.SeriesId}/Images/Primary`
```
I won't be making a PR though, as I hard coded stuff and don't want to deal with proper settings, other item types or Emby servers

**Comment by SandwichFox** [comment]
Oh wow thank you!

I think I will add this feature in the next major release!

Cheers!

**Comment by SandwichFox** [comment]
Added in [3.0.6](https://github.com/SandwichFox/MBCord/releases/3.0.6) as a beta feature. Emby Support will come
