### ISSUE TITLE
MBCord doesn't start

### ISSUE THREAD

**Issue by zeroquinc** [SandwichFox/MBCord#20]
**Describe the bug**
Yesterday I installed MBCord and it worked fine. Thanks for continuing to work on it as there isn't really any good alternative.
Today after I rebooted my PC MBCord won't open anymore. I have placed a GIF below to demonstrate.

https://i.imgur.com/9hP31d5.gif

I see that its running in Task Manager though, although I get no GUI and the Discord Rich Presence doesn't change after I play something.

Running as Administrator does the same thing.

**Expected behavior**
I expect the program to open and to start monitoring.

**Screenshots**
I added the screenshot above.

**Error**
* Attach the most recent log. Logs can be found by right clicking the tray application and clicking "Show Logs". Although it does its best to remove any, it's a good idea to give the logs a quick scrub to ensure there aren't any credentials/addresses
^ As I can't open the GUI I have no way of opening the logs, I tried searching in the mbcord folder but couldn't find any.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Server Type: Jellyfin
 - Version 10.8.7

EDIT: I removed this folder `\AppData\Roaming\mbcord` and it starts again and I have to set up my server again. I wonder if it will stop working again after a reboot though.

**Comment by SandwichFox** [comment]
Hmm... thats Strange, I will look into it.

**Comment by zeroquinc** [comment]
> Hmm... thats Strange, I will look into it.

First of all thanks for looking into it. Somehow that issue got fixed. But I have another issue now.

I have MBCord to start during Windows.

But when I start Jellyfin after a fresh boot, MBCord doesn't register the Rich Presence, **only** when I manually restart the app.

https://i.imgur.com/BrI7Bcc.gif

It continues to keep working when I restart the app once after a fresh boot, but it's still annoying cause sometimes I forget to do it. I vaguely remember the MBCord from the other maintainer had the same issue, but I never reported it.

**Comment by SandwichFox** [comment]
Could you enable **Debug Logging** and send me your latest log after rebooting again?

Your Logs can be found at: 

```
%appdata%/MBCord/logs
```

> I tried searching in the mbcord folder but couldn't find any.

It should be there

(Don't forget to hide sensible data!)

**Comment by zeroquinc** [comment]
```
[Tue Nov 15 2022 14:12:41 GMT+0100 (Central European Standard Time)] info: Starting app...
[Tue Nov 15 2022 14:12:41 GMT+0100 (Central European Standard Time)] info: DEBUG INFO:
Development Mode: false
Platform: win32 (Version 10.0.19045)
Architecture: x64
MBCord version: 3.0.5
Node version: 16.16.0
Electron version: 21.2.2
Chrome version: 106.0.5249
[Tue Nov 15 2022 14:12:41 GMT+0100 (Central European Standard Time)] debug: Attempting to log into server
[Tue Nov 15 2022 14:12:41 GMT+0100 (Central European Standard Time)] debug: {
 "port": "443",
 "protocol": "https",
 "serverType": "jellyfin",
 "isSelected": true,
 "ignoredViews": [],
 "serverId": "hidden",
 "serverName": "hidden"
}
[Tue Nov 15 2022 14:12:41 GMT+0100 (Central European Standard Time)] error: Failed to connect to Discord. Attempting to reconnect in 30 seconds
```

It doesn't seem to try to reconnect after 30s.

**Comment by SandwichFox** [comment]
Does Discord open after or before MBCord?

**Comment by zeroquinc** [comment]
They open at the same time, I think MBCord is like 0.5s faster. They both start when booting Windows. I have a NVMe drive so it boots up pretty fast.

The workaround is to start MBCord up a bit delayed I guess?

**Comment by SandwichFox** [comment]
A temporary fix, i guess... But I will look for a more permantent fix.

**Comment by SandwichFox** [comment]
I sadly didnt found any permanent fix for this problem :/ 
I will close this issue for now...

**Comment by zeroquinc** [comment]
Isn't it just as simple as to edit the part when MBCord starts with Windows to start it up delayed?

https://windowsloop.com/delay-startup-programs-with-task-scheduler/

Make it a 30s or 1min delay?
