### ISSUE TITLE
MBCord not working on linux

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [SandwichFox/MBCord#22]
**Describe the bug**
- deptap the .deb package (below codeblock)
- run chmod +x on appimage (below codeblock)
```
[bittersweet@candyshop ~]$ mbcord --trace-warnings

(mbcord:761878): Gtk-WARNING **: 18:22:24.079: Unknown key GTK_THEME in /home/bittersweet/.config/gtk-3.0/settings.ini
(node:761878) UnhandledPromiseRejectionWarning: Error: Cannot create an item in a locked collection
(Use `mbcord --trace-warnings ...` to show where the warning was created)
(node:761878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[761878:1118/182225.152886:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
- install appimage from aur (below codeblock)
```
MBCord: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory
```

**Expected behavior**
A window to open or normal startup

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Server Type: Jellyfin
 - Version: 10.8.7

**Extra Info**
I seem to be missing a shared lib, but I couldn't find any missing :/
Theming issue is irrelevant, gtk ignores invalid and haven't had an issue with my lazi/bad theme file before. :3

**Comment by SoftwareRat** [comment]
> **Describe the bug**
> 
>     * deptap the .deb package (below codeblock)
> 
>     * run chmod +x on appimage (below codeblock)
> 
> 
> ```
> [bittersweet@candyshop ~]$ mbcord --trace-warnings
> 
> (mbcord:761878): Gtk-WARNING **: 18:22:24.079: Unknown key GTK_THEME in /home/bittersweet/.config/gtk-3.0/settings.ini
> (node:761878) UnhandledPromiseRejectionWarning: Error: Cannot create an item in a locked collection
> (Use `mbcord --trace-warnings ...` to show where the warning was created)
> (node:761878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> [761878:1118/182225.152886:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
> ```
> 
>     * install appimage from aur (below codeblock)
> 
> 
> ```
> MBCord: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory
> ```
> 
> **Expected behavior** A window to open or normal startup
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Arch Linux x86_64
> 
>     * Server Type: Jellyfin
> 
>     * Version: 10.8.7
> 
> 
> **Extra Info** I seem to be missing a shared lib, but I couldn't find any missing :/ Theming issue is irrelevant, gtk ignores invalid and haven't had an issue with my lazi/bad theme file before. :3

Hello, I am the AUR maintainer
Run this command to check if the dependency is installed:
`ls /opt/appimages/mbcord | grep libffmpeg.so`
If it's there, try to run MBcord with this command:
`env APPDIR=/opt/appimages/mbcord /opt/appimages/mbcord/AppRun --no-sandbox %U`

And send the output here

**Comment by BitterSweetcandyshop** [comment]
after clean building mbcord-appimage
```
(3/3) Updating the desktop file MIME type cache...
[bittersweet@candyshop ~]$ ls /opt/appimages/mbcord | grep libffmpeg.so
libffmpeg.so
[bittersweet@candyshop ~]$ MBCord
MBCord: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory
[bittersweet@candyshop ~]$
```

```
[bittersweet@candyshop ~]$ env APPDIR=/opt/appimages/mbcord /opt/appimages/mbcord/AppRun --no-sandbox %U

(mbcord:868101): Gtk-WARNING **: 17:18:14.876: Unknown key GTK_THEME in /home/bittersweet/.config/gtk-3.0/settings.ini
(node:868101) UnhandledPromiseRejectionWarning: Error: Cannot create an item in a locked collection
(Use `mbcord --trace-warnings ...` to show where the warning was created)
(node:868101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[868101:1121/171815.943666:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
