### ISSUE TITLE
Bilder von Serien oder Filme werden nicht anzeigt in Discord

### ISSUE THREAD

**Issue by ghost** [SandwichFox/MBCord#35]
**Describe the bug**
Die Bilder von Serien oder Filme werden nicht auf Discord angezeigt. 
Hab bei drei verschiedenen Serien/Filme nachgeschaut und da sieht man nichts, auf den Screenshots sieht man dies auch. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/83706294/208389127-43146004-909c-4033-8e3f-b6353e47ddac.png)
![grafik](https://user-images.githubusercontent.com/83706294/208389210-44dfd2fb-669c-48ca-8866-6de241f79eb6.png)
![grafik](https://user-images.githubusercontent.com/83706294/208389283-1ae860a6-4236-446d-81f7-1e560c474028.png)

**Error**
```
[Mon Dec 19 2022 10:03:46 GMT+0100 (Mitteleuropäische Normalzeit)] info: Starting app...
[Mon Dec 19 2022 10:03:46 GMT+0100 (Mitteleuropäische Normalzeit)] info: DEBUG INFO:
Development Mode: false
Platform: win32 (Version 10.0.19044)
Architecture: x64
MBCord version: 3.0.6
Node version: 16.17.1
Electron version: 22.0.0
Chrome version: 108.0.5359
[Mon Dec 19 2022 10:03:46 GMT+0100 (Mitteleuropäische Normalzeit)] info: Connected to Discord (Server type: jellyfin)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Server Type: Jellyfin
 - Version 3.0.6

**Comment by SandwichFox** [comment]
Das problem ist mir bekannt. Da die Filme und Serien jeweils andere ID namen besitzen. Das werde ich in der nächsten version fixen

**Comment by SandwichFox** [comment]
Ich hab den fehler gefunden und gefixt. wird in dem Nächsten Release dabei sein.

**Comment by ghost** [comment]
Mir ist auf gefallen das man nicht die Locale IP nutzen darf sondern man muss halt die öffentliche IP oder Domain halt nutzen.

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/83706294/210177438-43a4dc0d-98d1-4b21-aea7-685a54541a82.png)
Da sieht man es jz auch

**Comment by zeroquinc** [comment]
> Mir ist auf gefallen das man nicht die Locale IP nutzen darf sondern man muss halt die öffentliche IP oder Domain halt nutzen.

I have noticed this too. Is there any fix for this? I only use Jellyfin with local IP.
