### ISSUE TITLE
only works on windows startup if i restart app first

### ISSUE THREAD

**Issue by reitenth** [SandwichFox/MBCord#62]
on windows startup, it only displays if i restart the app first. i saw this https://github.com/SandwichFox/MBCord/issues/20 and i tried setting it to start a min after startup in task scheduler but that does not seem to have worked. 

i either get "Failed to get sessions: Error: connect ECONNREFUSED 192.168.1.136:8096" or "Failed to get sessions: Error: connect ETIMEDOUT 192.168.1.136:8096"

**Comment by SandwichFox** [comment]
Hmm, it seems like the program cant connect to your Jellyfin/Emby instance on first start. Does it work after an restart of the app?

**Comment by SandwichFox** [comment]
I will close this Issue, for now. If this problem still exists please reopen this issue
