### ISSUE TITLE
image not loading and pause not working

### ISSUE THREAD

**Issue by reitenth** [SandwichFox/MBCord#73]
![image](https://user-images.githubusercontent.com/94771708/222806865-e71cc2bc-987e-47fa-881e-8fceab06f8be.png)
image not loading, nor does it changed to paused when media is paused. 

here is debug log

https://gist.github.com/reitenth/f4453a40cbeeee8f383cee91a2477255

**Comment by SandwichFox** [comment]
Could you maybe send me the Discord console log if possible?
